apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  namespace: monitoring
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: example-app
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.41.0
spec:
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: example-app
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
